version: '3'

services:
  app:
    image: ppaquin/dev-sutom-api:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
      - MONGO_URI=mongodb://db:27017
    networks:
      - my-network
  db:
    image: mongo:latest
#    ports:
#      - "27017:27017"
    volumes:
      - my_db_data:/data/db
    networks:
      - my-network
volumes:
  my_db_data:
networks:
  my-network:
#    driver: bridge